CREATE TRIGGER USERID_TRIG 
BEFORE/AFTER INSERT ON USER_DETAILS
FOR EACH ROW
    BEGIN
    INSERT INTO USER_DETAILS VALUES ('HARSHA','PPPPPP','KSDSDJSDN',98,'TERERR')
    -- SELECT HARSHA.nextval
    -- INTO new.USER_ID
    -- FROM USER_DETAILS;
    END;

-- SHOW USERID_SEQUENCE;

-- drop SEQUENCE USERID_SEQUENCE;