
  CREATE TABLE "MSSUSER04"."APP_TABE" 
   ("APP_ID" NUMBER, 
"APP_DETAILS" VARCHAR2(50 CHAR), 
"VERSION" VARCHAR2(50 CHAR), 
 PRIMARY KEY ("APP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_MSSORCL"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_MSSORCL" ;
 

  CREATE OR REPLACE TRIGGER "MSSUSER04"."APP_T" 
BEFORE INSERT ON APP_Tabe
FOR EACH ROW
BEGIN
  SELECT APP_id_seq.nextval
  INTO :new.APP_id
  FROM dual;
END;

